#+TITLE: Church Presenter
#+AUTHOR: Chris Cochrun

* Church Presenter
This is an attempt at building a church presentation application in Qt/QML. QML provides a very powerful and easy declarative way of creating a UI so it should also be a very simple method of creating on screen slides and presentations. This experiment is to see how difficult it is to rebuild these applications in QML as opposed to other more complicated systems. After digging through the source code of OpenLP, I discovered they are essentially creating a web server and rendering a webpage onto the screen to show slides. This felt like a waste of resources and added complexity when something so simple and useful as QML exists.

** Features (planned are in parentheses)
- Presents songs lyrics with image and video backgrounds
- Presents slides
- (Custom slide builder)
- (Simple song creation with a powerful text parser)

* Build and Run
First get the source code

Then into the root directory.
#+BEGIN_SRC
cd church-presenter
#+END_SRC

Then build.
#+BEGIN_SRC
cmake -B build/ . && make --dir build/
#+END_SRC

Then run.
#+BEGIN_SRC
./build/bin/presenter
#+END_SRC
