pub mod ffmpeg;
mod file_helper;
pub mod image_model;
pub mod models;
pub mod presentation_model;
pub mod song_model;
pub mod schema;
mod service_thing;
mod settings;
pub mod slide_model;
mod slide_obj;
pub mod video_model;
pub mod ytdl;
// mod video_thumbnail;
