//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "songs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub title: String,
    pub lyrics: Option<String>,
    pub author: Option<String>,
    pub ccli: Option<String>,
    pub audio: Option<String>,
    pub vorder: Option<String>,
    pub background: Option<String>,
    #[sea_orm(column_name = "backgroundType")]
    pub background_type: Option<String>,
    #[sea_orm(column_name = "horizontalTextAlignment")]
    pub horizontal_text_alignment: Option<String>,
    #[sea_orm(column_name = "verticalTextAlignment")]
    pub vertical_text_alignment: Option<String>,
    pub font: Option<String>,
    #[sea_orm(column_name = "fontSize")]
    pub font_size: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
